---
title: "Mobbing Data"
author: "Justin Mann"
date: "2024-09-11"
output: html_document
---

## Libraries
```{r}
library(tidyverse)
library(vegan)
```


## Import Data

```{r df}
df <- read.csv("MobbingSpeciesData_F24.csv", h=T)
```

```{r diversity and richness}
#Spread long format data to wide format
wdf <- df %>% spread(key = Species, Count)

#Convert NAs to zeros
wdf[is.na(wdf)] <-0

#Create a sequential numeric vector for observation ID
wdf$obs <- 1:nrow(wdf)
wdf <- wdf %>% select(obs, everything()) #move obs to column one

#Create a covariate dataframe with treatment factor
cov <- wdf %>% select(Day,Trial,Treatment)

#Remove factors from the wide form dataframe
wdf <- wdf[,c(1,5:31)]

#Append Shannon diversity and species richness to covariate dataframe
cov$Trial <- 1:nrow(cov) #Number trials 1-9
cov$H <- diversity(wdf)
cov$spp <- specnumber(wdf)
```


```{r audio.df}
#Read in bioacoustics data
audio.df <- read.csv("TotalMobbingSelections.csv", h=T)

#Group by trial number
byTrial.df <- audio.df %>% group_by(Trial)

#Create a vector with the average max entropy per trial
EntropyByTrial <- byTrial.df %>% summarise(MaxEntropy = mean(Max.Entropy..bits.), AvgEntropy = mean(Avg.Entropy..bits.))

#Join average max entropy per trial to the covariate dataframe
newCov.df <- full_join(EntropyByTrial, cov, by = join_by(Trial))
```


```{r diversity ANOVA}
#ANOVA comparing diversity by Treatment
H.aov <- aov(H ~ Treatment, data = cov)
summary(H.aov)
```


```{r richness ANOVA}
#ANOVA comparing species richness by Treatment
spp.aov <- aov(spp ~ Treatment, data = cov)
summary(spp.aov)
```


```{r maxEntropy}
#ANOVA comparing species richness by Treatment
maxEntropy.aov <- aov(MaxEntropy ~ Treatment, data = newCov.df)
summary(maxEntropy.aov)
```

